# Generated by Django 3.2.8 on 2021-10-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notdiensture_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
